// Generates dist/index.mjs: a thin ESM wrapper around the UMD bundle.
// There is exactly one runtime copy of the library either way, so this
// cannot cause the dual-package hazard.
const fs = require("fs");
const path = require("path");

const bundlePath = path.resolve(__dirname, "../dist/bundle.js");
const outPath = path.resolve(__dirname, "../dist/index.mjs");
const dtsPath = path.resolve(__dirname, "../dist/index.d.ts");
const dmtsPath = path.resolve(__dirname, "../dist/index.d.mts");

delete require.cache[require.resolve(bundlePath)];
const lib = require(bundlePath);
const names = Object.keys(lib);

if (names.length === 0) {
    throw new Error("lightjx: dist/bundle.js has no named exports; refusing to write an empty dist/index.mjs");
}

const lines = [
    "// Generated by scripts/build-esm.js - do not edit directly.",
    "import lightjx from './bundle.js';",
    "",
    ...names.map((name) => `export const ${name} = lightjx.${name};`),
    "",
    "export default lightjx;",
    "",
];

fs.writeFileSync(outPath, lines.join("\n"));
console.log(`lightjx: wrote dist/index.mjs with named exports: ${names.join(", ")}`);

// The declarations are plain `declare class`/`export { ... }` syntax with no
// CJS-specific constructs, so a byte-identical .d.mts copy is valid ESM
// types. This is required for the "import" condition's types to resolve
// as ESM under moduleResolution node16/nodenext - without it, TS treats
// the shared .d.ts as CJS-format and reports the package as "masquerading
// as CJS" (see arethetypeswrong FalseCJS).
fs.copyFileSync(dtsPath, dmtsPath);
console.log("lightjx: wrote dist/index.d.mts (copy of dist/index.d.ts for ESM type resolution)");
